# Generated by Django 4.0.4 on 2022-04-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedsession',
            name='user',
        ),
        migrations.AddField(
            model_name='logentry',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='log_manager.loggedsession'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='log_manager.loggeduser'),
        ),
    ]
